### ISSUE TITLE
Test component events through Storybook actions

### ISSUE THREAD

**Issue by alejandroiglesias** [NicholasBoll/cypress-storybook#16]
Sorry if the question is too obvious, but I'm new to Storybook + Cypress. Is there a way to test the component events as Storybook actions? I'm thinking something similar to this:

```jsx
<Button onClick={action('clicked')}>Button</Button>
```
```js
cy.get('button').click()
cy.action('clicked').should('have.length', 1)  // I just made up this one as an example
```
I didn't found anything related to Storybook actions implemented in the code, so I'm not sure if there isn't currently a way to test events like this or if it's unnecessary and there's a much simpler way to approach it. 
Thanks in advance.

**Comment by jogelin** [comment]
@alejandroiglesias any news ?
I am also looking for a way to catch actions. I read the code of the action plugin and I see they are using the channel provided by storybook to communicate between the story and the actions panel. 

I am looking for a way to listen for those events...but not found yet

For the moment I am adding my actions in the template (hidden) then I use crypress to check if the element exist in the DOM...

**Comment by NicholasBoll** [comment]
There is a pull request to this effect: https://github.com/NicholasBoll/cypress-storybook/pull/4

I haven't merged it yet because I feel actions should be tied to sinon stubs. I'll see what I can come up with.

**Comment by NicholasBoll** [comment]
Fixed in https://github.com/NicholasBoll/cypress-storybook/releases/tag/v0.3.0
