### ISSUE TITLE
Not compatible with IE11 (but easy fix?)

### ISSUE THREAD

**Issue by benjadrejer** [NicholasBoll/cypress-storybook#22]
My team & I find this package quite helpful for cypress unit-testing react component in storybook.
We ran into an issue with IE11, though, that causes storybook to break when importing this package.

It seems to be related to the single case of shorthand-object-properties in common.js, where it sets `updatedArgs` as a shorthand.
Changing this to simply `updatedArgs: updatedArgs,` fixes IE11 compatibility.

It's a super minor change for a pretty significant gain, would be cool to get implemented directly in the package.

**Comment by NicholasBoll** [comment]
Thanks for bringing this issue up. I'm open to a pull request!

**Comment by benjadrejer** [comment]
Cool, I've made a pull request with the change. Appreciate you being open to this :+1:
